version: '3.9'

services:
  ammerli-db:
    image: postgres:16
    container_name: ammerli-db
    restart: always
    volumes:
      - ammerli-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: 'UTC'
    ports:
      - '${DATABASE_PORT}:5432'
    networks:
      - ammerli-network

  ammerli-redis:
    image: redis/redis-stack:latest
    container_name: ammerli-redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
      - '8001:8001'
    volumes:
      - ammerli-redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    environment:
      REDIS_ARGS: '--requirepass ${REDIS_PASSWORD}'
    networks:
      - ammerli-network

  ammerli-maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    container_name: ammerli-maildev
    ports:
      - '${MAIL_CLIENT_PORT}:1080'
      - '${MAIL_PORT}:1025'
    networks:
      - ammerli-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: ammerli-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ammerli-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: ammerli-kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Essential: Maps the protocol to the listener name
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      # Advertised listeners: how clients reach the broker
      # 1. localhost for your NestJS app running on your Mac/Windows
      # 2. ammerli-kafka for other containers inside the docker network
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://ammerli-kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ammerli-network

volumes:
  ammerli-db-data:
  ammerli-redis-data:

networks:
  ammerli-network:
    driver: bridge
